# PostgreSQL Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/student
spring.datasource.username=postgres
spring.datasource.password=123

# Logging
logging.level.org.springframework.jdbc.core=DEBUG